### ISSUE TITLE
Requirements for rest server are missing

### ISSUE THREAD

**Issue by roma-guru** [jpospychala/fx-market#1]
On the first step from **README.md**:

```
(zeep-venv) ± node rest_app.js
module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/r.voropaev/Desktop/fx-market/src/rest_app.js:2:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by jpospychala** [comment]
good point.
please update, and before invoking node, please run npm install in src directory.
Then node should install just fine. I updated the README as well
